#include <stdio.h>
#include "ListaStrings.h"

typedef enum {COMANDOENLUGAREQUIVOCADO, PALABRAENLUGAREQUIVOCADO, CANTIDADDEPARAMETROSINCORRECTA, PALABRAEQUIVOCADA, PALABRADEBESERNATURAL,
NOEXISTEENLISTAEXPRESIONES, NOEXISTEENLISTAEXPRESIONESPRIMERO, NOEXISTEENLISTAEXPRESIONESSEGUNDO, PALABRANOALFABETICA, ARCHIVONODAT, NOEXISTEARCHIVO} errores;

//Muestra por pantalla mensajes de error según el comando y el tipo de error
void error (errores codigo, int comando, ListaStrings L);


